server:
  port: 7003

# Eureka配置
eureka:
  instance:
    hostname: eureka7003 # eureka服务端实力名称
  client:
    register-with-eureka: false # 表示是否想eureka注册中心注册自己
    fetch-registry: false # false表示自己为注册中心
    service-url: # 监控页面
      defaultZone: http://eureka7001:7001/,http://eureka7002:7002/,http://eureka7003:7003/
